{% set name = "pyfakefs" %}
{% set version = "5.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: a734fb70a55acdda41469d5ea8e169b0a37bf28618326722adc09faeb65b0f1d
  # For the test suite
  - url: https://github.com/pytest-dev/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 3c15b70c3e7bc92c87327380e643f6c1bb636172c9d987ffa2fe2585a6ca3cad
    folder: gh

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pyfakefs
  source_files:
    - gh/pyfakefs
  requires:
    - pip
    - pytest >=6.2.5
  commands:
    - pip check
    # Set PYTHONPATH to use local pyfakefs directory for tests
    - cd gh
    - python -m pyfakefs.tests.all_tests
    - python -m pyfakefs.tests.all_tests_without_extra_packages
    - python -m pytest pyfakefs/pytest_tests/pytest_plugin_test.py

about:
  home: https://github.com/pytest-dev/pyfakefs
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: A fake file system that mocks the Python file system modules.
  description: |
    Pyfakefs implements a fake file system that mocks the Python file system
    modules. Using pyfakefs, your tests operate on a fake file system in
    memory without touching the real disk. The software under test requires
    no modification to work with pyfakefs. pyfakefs works with Linux, Windows
    and macOS.
  doc_url: https://pytest-pyfakefs.readthedocs.io
  dev_url: https://github.com/pytest-dev/pyfakefs

extra:
  recipe-maintainers:
    - tswast
    - thewchan
