{% set name = "pyfakefs" %}
{% set version = "5.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a549b32865aa97d8ba6538285a93816941d9b7359be2954ac60ec36b277e879

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - pyfakefs/tests
    - pyfakefs/pytest_tests
  imports:
    - pyfakefs
  commands:
    - pip check
    # tox.ini#L12-L14
    - python -m pyfakefs.tests.all_tests
    - python -m pyfakefs.tests.all_tests_without_extra_packages
    - python -m pytest pyfakefs/pytest_tests/pytest_plugin_test.py
  requires:
    - pip
    - pytest

about:
  home: https://github.com/pytest-dev/pyfakefs
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: A fake file system that mocks the Python file system modules.
  description: |
    Pyfakefs implements a fake file system that mocks the Python file system
    modules. Using pyfakefs, your tests operate on a fake file system in
    memory without touching the real disk. The software under test requires
    no modification to work with pyfakefs. pyfakefs works with Linux, Windows
    and macOS.
  doc_url: https://pytest-pyfakefs.readthedocs.io
  dev_url: https://github.com/pytest-dev/pyfakefs

extra:
  recipe-maintainers:
    - tswast
    - thewchan
