{% set name = "pyfakefs" %}
{% set version = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87a9819dafa2b210a26d9453aea1903eb88bd76a2425053a8f4ba6245777c498

build:
  noarch: python
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyfakefs

about:
  home: https://github.com/jmcgeheeiv/pyfakefs
  license: Apache-2.0
  license_file: COPYING
  summary: 'A fake file system that mocks the Python file system modules.'

  description: |
    pyfakefs implements a fake file system that mocks the Python file system
    modules. Using pyfakefs, your tests operate on a fake file system in
    memory without touching the real disk. The software under test requires
    no modification to work with pyfakefs. pyfakefs works with Linux, Windows
    and MacOS.

  doc_url: http://jmcgeheeiv.github.io/pyfakefs/
  dev_url: https://github.com/jmcgeheeiv/pyfakefs

extra:
  recipe-maintainers:
    - tswast
