{% set name = "pyfakefs" %}
{% set version = "6.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 059fd0b2174bfeed499ecb0a59bccff557f267cc6d885afc0e5b76e78b6d50da

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.3
  run:
    - python
  run_constrained:
    # these are used to test pandas-specific patches to allow
    # pyfakefs to work with pandas2
    # we use the latest version to see any problems with new versions
    - pandas >=2.2.3
    - xlrd >=2.0.1
    - openpyxl >=3.1.5

# >   raise OSError(err_no, message, filename)
# E   FileNotFoundError: [Errno 2] No such file or directory: '$PREFIX/lib/python3.10/site-packages/pyfakefs/tests/skipped_pathlib.py'
{% set deselect_tests = " --deselect=tests/fake_filesystem_unittest_test.py::AdditionalSkipNamesTest::test_open_succeeds" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/fake_filesystem_unittest_test.py::AdditionalSkipNamesModuleTest::test_open_succeeds" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/fake_filesystem_test.py::FakePathModuleTest::test_realpath_allow_missing" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/fake_open_test.py::SkipOpenTest::test_open_in_skipped_module" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/fake_pathlib_test.py::SkipPathlibTest::test_exists" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/fake_pathlib_test.py::SkipPathlibTest::test_open_in_skipped_module" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/fake_pathlib_test.py::SkipPathlibTest::test_read" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/fake_pathlib_test.py::FakeFilesystemChmodTest::test_is_file_for_unreadable_dir_windows" %}
test:
  imports:
    - pyfakefs
  commands:
    - pip check
    - pytest --pyargs pyfakefs {{ deselect_tests }}
  requires:
    - pip
    - pytest >=6.2.5
    - pytest-xdist

about:
  home: https://github.com/pytest-dev/pyfakefs
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: A fake file system that mocks the Python file system modules.
  description: |
    Pyfakefs implements a fake file system that mocks the Python file system
    modules. Using pyfakefs, your tests operate on a fake file system in
    memory without touching the real disk. The software under test requires
    no modification to work with pyfakefs. pyfakefs works with Linux, Windows
    and macOS.
  doc_url: https://pytest-pyfakefs.readthedocs.io
  dev_url: https://github.com/pytest-dev/pyfakefs

extra:
  recipe-maintainers:
    - tswast
    - thewchan
