travis:
  secure:
    BINSTAR_TOKEN: lsC6grrEqHbjovgOu4Fr5uhArbNaXsLHKCrveBLr1vUuisn8Jl4KwPEV2EiX6FYdkmdAzRRW/BwHa16APhCzMyljT24QUFicxkAPJfFvy1cEs1jPPKqWVrn9wjcmvgmu1Nqihdiv5/DOHohcnHcIGswpyCwv4R1nCg3ef8BXq/IyU+894XQHl7WdYY/7t8X9Cwz1S+73BSu6v3n249JZlZVvtvaAXHlqnF/kLPllPX0EhQREsGubSecyGY107G/y5v5h48NwsBJ6y+ULERBXpkdLBBnq7NSmMgP7mqYq4LJ90bZEFSP604SeUhS+f3tIRVzx0v223K8kLnpPfKD39KGF5fgktyfg9l4/+SBnXV8Ij3fEqzZxfXlxNWkMcAfFdj58Nnk3tZwbqFXR1gbuHmCwZ4zNVDQGZnxmYHng95ESkwkbSDKZBWhBy+OtEu41NzeIE6tULO7MTUcJz0M7zNUvVCKb+gJksmcr8IOXpfMiIy69aDodDLZ72snbPTG7+MT49pOHDYgrYTuhDkzEbNuTyd5DM24nPrS2t3joyyjQHEGrBOPmroyGaZSivmefBI/X7PgMcsjlsOjQzzm6yLPsv9xHZc5vH2rKkXUUFWGnaFFmiOTCvXm0MroVkhyZbB0ctIg99ym5q2StqZgicU2EDkhG1hZorI7m0mnjwJk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
